config/routes.rb
Rails.application.routes.draw do
  #resources :appointments
  get 'personas/index'
  get 'home/index'
  #get 'articulos/index'

  #resources :articulos
  resources :personas do 
    resources :appointments
  end
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :persona
end

app/models/persona.rb
class Persona < ApplicationRecord
    validates :name, presence: { :message => "No puede estar vacio"}
    validates :last_name, presence: { :message => "No puede estar vacio"}
    validates :email, presence: { :message => "No puede estar vacio"}
    validates :password, presence: { :message => "No puede estar vacio"}, length: {minimum: 8, :message => "Es demaciado corta, minimo 8 caracteres"}
    validates :date, presence: { :message => "No puede estar vacio"}
    has_many :appointment
    accepts_nested_attributes_for :appointment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit

  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.create(appointment_params)
    @persona = Persona.find(params[:persona_id])
    
    redirect_to @persona
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :status, :persona_id)
    end
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  def index
  end
  
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  def index
    @personas = Persona.all.order("created_at")
  end

  def new
    @boton = "Registrar"
    @persona = Persona.new  
  end

  def create
    @persona=Persona.new(persona_params)
    if @persona.save
      redirect_to personas_path
    else
      render 'new'
    end
  end

  def edit
    @boton = "Editar"
    @persona = Persona.find(params[:id])
  end

  def update
    @persona = Persona.find(params[:id])
    if @persona.update(persona_params)
      redirect_to personas_path, notice: "Cita modificada correctamente"
    else
      render 'edit'
    end
  end

  def show
    @persona = Persona.find(params[:id])
  end

  def destroy
    @persona = Persona.find(params[:id])
    @persona.destroy
    redirect_to personas_path, notice: "Cita eliminada correctamente"
  end

  private def persona_params
    params.require(:persona).permit(:name, :last_name, :email, :password, :date, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/appointments/_form.html.erb
<%= form_for([@persona, @persona.]) do |form| %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>articulos#edit</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/articulos/index.html.erb
<h1>Articulos#index</h1>
<p>Find me in app/views/articulos/index.html.erb</p>

app/views/articulos/new.html.erb
<h1>Articulos#new</h1>
<p>Find me in app/views/articulos/new.html.erb</p>

app/views/articulos/show.html.erb
    <h1>articulos#show</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/index.html.erb
<div class="divider">
    <div class="container mt-5 mb-5">
        <div class = 'row'>
            <div class = 'col'>
                <h1>Bienvenido, realice su registro!</h1>
            <div>
        <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col">
            <img src='https://images.pexels.com/photos/4270940/pexels-photo-4270940.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260' alt='Img dentista' height = '500'>
            </div>
            <div class="col justify-content-md-center">
            <h3> Haga clic debajo para agendar cita!</h3>
            <div class = 'container'>
                <div class = 'row justify-content-md-center mt-5 mb-5'>
                <div class='col col-lg-5'>
                    <%= link_to "<p  class='btn btn-outline-success'>Agendar cita!</p>".html_safe, new_persona_path %>
                </div>
                </div>
            </div>
            </div>
            
        </div>
        
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    
  </head>

  <body>
  
  <% if !flash.empty? %>
        <%= flash.each do |key, value| %>
          <div class="alert alert-info">
            <%= value %>
          </div>
        <%end%>
  <%end%>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Sweet Smile</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/personas/new">Agendar cita</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/personas">Ver citas</a></li>
                    </ul>
                </div>
            </div>
    </nav>
    <div>
      <%= yield %>
    </div>
  </body>
  <footer class="bg-light text-center text-lg-start">
    <div class='row'>
      <div class='navbar fixed-bottom'>
        <div class="col-sm-12 ">
          <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            Sweet Smile© 
          </div>
        </div>
      </div>
    </div>
</footer>
</html>

app/views/personas/_form.html.erb
<%= form_for @persona do |f| %>
    <% if @persona.errors.any? %>
        <div id="Errores">
            <h2>Se han producido los siguientes errores</h2>
            <ul>
                <% @persona.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class='container justify-content-md-center'>
        <div class="form-group col-md-6">
            <%= f.label "Nombre(s)"%> <br>
            <%= f.text_field :name, class: 'form-control mb-2' %> <br>
        </div>
        <div class="form-group col-md-6">
            <%= f.label "Apellido" %> <br>
            <%= f.text_field :last_name, class: 'form-control mb-2' %> <br>
        </div>
        <div class="form-group col-md-6">
            <%= f.label "E-mail" %><br>
            <%= f.email_field :email, class: 'form-control mb-2' %> <br>
        </div>
        <div class="form-group col-md-6">
            <%= f.label "Contraseña" %> <br>
            <%= f.password_field :password, class: 'form-control mb-2'%> <br> 
        </div>
        <div class="form-group col-md-6">
            <%= f.label "Fecha de consulta" %> <br>
            <%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control'%> <br> 
        </div>
        <div class="form-group col-md-6">
            <%= f.label "Estatus" %> <br>
            <%= f.select :status, options_for_select([['Activo','Activo'],['Terminado','Terminado']], params[:area]),{}, class: 'form-control mb-2' %> <br> 
        </div>
        <%= f.submit "#{@boton} Usuario", class: 'btn btn-success   '%> <br>
    </div>
<% end %>

app/views/personas/edit.html.erb
<div class='container mt-5 mb-5'>
<h1>Actualiza tus datos!</h1>
<p>Escribe tus datos debajo para actualizar</p>
</div>
    <%= render 'form'%>

app/views/personas/index.html.erb
<div class='container mt-5 mb-5'>
<div class = 'row justify-conten'>
  <div class='col-9'>
  <h1>Tabla de citas</h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">E-mail</th>
        <th scope="col">Fecha de consulta</th>
        <th scope="col">Estatus</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      <% @personas.each do |per| %>
          <tr>
              <th scope="row"><%= per.id %></th>
              <td><%=per.name + ' '+ per.last_name%></td>
              <td><%= per.email %></td>
              <td><%= per.date %></td>
              <td><%= per.status%></td>
              <td>
                <%= link_to "<i class='bi bi-trash-fill btn btn-outline-danger'></i>".html_safe, per, :method => :delete, data: {confirm:"¿Seguro que quieres eliminar la cita?"} %>

                <%= link_to "<i class='bi bi-pencil-square btn btn-outline-warning'></i>".html_safe, edit_persona_path(per) %>
          </tr>
      <% end %>
      
    </tbody>
  </table>
</div>
</div>
<div class= "container">
  
  <%= link_to "<i class='bi bi-file-earmark-plus-fill btn btn-outline-success'></i>".html_safe, new_persona_path %>
  
</div>    

app/views/personas/new.html.erb
<div class='container mt-5 mb-5'>
<h1>Registrate!</h1>
<p>Escribe tus datos debajo para registrarte</p>
</div>
    <%= render 'form'%>

app/views/personas/show.html.erb
    <h1><%= @persona.name + ' '+ @persona.last_name %></h1>

<p>Creado el: <%= @persona.created_at.strftime("%d-%m-%Y") %></p>
<p>E-mail: <%= @persona.email  %></p>
<%= link_to "Editar", edit_persona_path(@persona) %>
<%= link_to "Eliminar", @persona, :method => :delete, data: {confirm:"¿Seguro que quieres eliminar el articulo?"} %>